# Generated by Django 5.1 on 2024-09-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "test",
                "managed": False,
            },
        ),
    ]
