# Generated by Django 5.1 on 2024-09-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet_plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodFoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "good_foods",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
